# Generated by Django 4.0.1 on 2022-07-04 13:54

import banners.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Заголовок баннера')),
                ('photo', models.ImageField(help_text='Загрузите фотографию не более 3Мб, допустимый формат: jpeg, jpg, png, svg', null=True, upload_to=banners.models.banners_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'svg'])], verbose_name='иконка баннера')),
                ('description', models.TextField(blank=True, help_text='Опишите что это за баннер', verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='статус активности')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('product_banner', models.ForeignKey(blank=True, help_text='выберите товар, которому соответствует баннер', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'баннер',
                'verbose_name_plural': 'баннеры',
                'db_table': 'Banners',
            },
        ),
    ]
