# Generated by Django 4.0.1 on 2022-08-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_number_visa'),
        ('accounts', '0002_alter_clientproductview_options_client_full_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.Order', verbose_name='Заказы'),
        ),
    ]
