# Generated by Django 4.0.1 on 2022-07-28 08:30

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=[pathlib.PurePosixPath('/home/pavlove/Рабочий стол/python_django_team9/fixtutes/admin_fixtures')], verbose_name='файл фикстур')),
            ],
            options={
                'verbose_name': 'файл фикстур',
                'verbose_name_plural': 'файлы фикстур',
            },
        ),
    ]
