# Generated by Django 4.0.1 on 2022-07-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_import', '0002_alter_fixturefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturefile',
            name='name',
            field=models.CharField(default='NON', max_length=1000, verbose_name='название товара'),
        ),
        migrations.AddField(
            model_name='fixturefile',
            name='status',
            field=models.CharField(choices=[('y', 'processed'), ('n', 'not processed')], default='n', max_length=1, verbose_name='status'),
        ),
    ]
