# Generated by Django 4.0.1 on 2022-07-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_import', '0003_fixturefile_name_fixturefile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixturefile',
            name='status',
            field=models.CharField(choices=[('y', 'processed'), ('n', 'not processed')], default='n', max_length=1, verbose_name='статус'),
        ),
    ]
