# Generated by Django 4.0.1 on 2022-07-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_import', '0005_alter_fixturefile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturefile',
            name='extension',
            field=models.CharField(default='NON', max_length=10, verbose_name='расширение файла'),
        ),
    ]
