# Generated by Django 4.0.1 on 2022-07-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_import', '0006_fixturefile_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturefile',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='очередность'),
        ),
    ]
