# Generated by Django 4.0.1 on 2022-07-04 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=39, verbose_name='название')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='описание')),
                ('discount', models.FloatField(default=0, verbose_name='скидка')),
            ],
            options={
                'verbose_name': 'акция',
                'verbose_name_plural': 'акции',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=39, verbose_name='название')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='описание')),
                ('city', models.CharField(max_length=39, verbose_name='город')),
                ('street', models.CharField(max_length=50, verbose_name='улица')),
                ('house_number', models.IntegerField(default=0, verbose_name='номер дома')),
                ('phone', models.CharField(max_length=15, verbose_name='телефон')),
                ('email', models.EmailField(max_length=256, verbose_name='email')),
                ('rating', models.IntegerField(default=0, verbose_name='рейтинг')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.promotions', verbose_name='акция')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
            },
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shops', verbose_name='магазин')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='счетчик')),
                ('price_in_shop', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена')),
                ('special_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='специальная цена')),
                ('photo_url', models.TextField(blank=True, max_length=500, verbose_name='фото url')),
                ('sale', models.IntegerField(default=0, verbose_name='скидка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_product', to='products.product', verbose_name='товар')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.promotions', verbose_name='акция')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shops', verbose_name='магазины')),
            ],
            options={
                'verbose_name': 'товар в магазине',
                'verbose_name_plural': 'товары в магазинах',
            },
        ),
        migrations.CreateModel(
            name='ShopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default.jpg', upload_to='shops_photo', verbose_name='фото магазина')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shops', verbose_name='магазин')),
            ],
            options={
                'verbose_name': 'фото магазина',
                'verbose_name_plural': 'фото магазинов',
            },
        ),
    ]
