# Generated by Django 4.0.1 on 2022-07-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_promotion_group'),
        ('promotions', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopphoto',
            options={'verbose_name': 'фото магазина', 'verbose_name_plural': 'фото магазина'},
        ),
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'verbose_name': 'товар в магазине', 'verbose_name_plural': 'товары в магазине'},
        ),
        migrations.AddField(
            model_name='shops',
            name='products',
            field=models.ManyToManyField(related_name='shops', related_query_name='shop', through='shops.ShopProduct', to='products.Product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='shopphoto',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='shops_photo', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='shopphoto',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_photos', related_query_name='shop_photo', to='shops.shops', verbose_name='магазин'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='photo_url',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_product', related_query_name='shop_product', to='products.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='promotion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='shop_product', related_query_name='shop_product', to='promotions.promotions', verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='sale',
            field=models.IntegerField(default=0, verbose_name='sale'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_product', related_query_name='shop_product', to='shops.shops', verbose_name='магазин'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='special_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='спец-цена'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='promotion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='shops', related_query_name='shop', to='promotions.promotions', verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='рэйтинг'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_users', related_query_name='shop_user', to='shops.shops', verbose_name='магазин'),
        ),
        migrations.DeleteModel(
            name='Promotions',
        ),
    ]
