# Generated by Django 4.0.1 on 2022-08-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shopphoto_options_alter_shopproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
