# Generated by Django 4.0.1 on 2022-07-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_visa',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Номер карты оплаты'),
        ),
    ]
