# Generated by Django 4.0.1 on 2022-08-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_number_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ordercopyproduct',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
