# Generated by Django 4.0.1 on 2022-07-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_promotion_group'),
        ('accounts', '0001_initial'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'verbose_name': 'Товар из корзины', 'verbose_name_plural': 'Товары из корзины'},
        ),
        migrations.AddField(
            model_name='basketitem',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Стоимость без скидки'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='seller',
            field=models.CharField(blank=True, max_length=100, verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='session',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ключ сессии'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='accounts.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='qty',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
