# Generated by Django 4.0.1 on 2022-08-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_promotion_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(default='products_photo/default.png', upload_to='products_photo/', verbose_name='фото товара'),
        ),
    ]
