# Generated by Django 4.0.1 on 2022-08-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userreviews',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
